package spdvid.bkportal_di_dam.panels;

import java.awt.Font;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import spdvid.bkportal_di_dam.MainScreen;
import spdvid.bkportal_di_dam.data.DataAccess;
import spdvid.bkportal_di_dam.dto.Alojamiento;
import spdvid.bkportal_di_dam.panels.DataPanel;
import spdvid.bkportal_di_dam.tablemodels.AllotjamentTableModel;
import spdvid.bkportal_di_dam.tablemodels.AllotjamentTableModel;

/**
 *
 * @author Fer
 */
public class SecondaryScreen extends javax.swing.JPanel {
    private DataAccess da = new DataAccess();
    private MainScreen JFrameMainScreen = null;
    
//    String usuari;
//    private javax.swing.JList<Alojamiento> lstListaAlojamientos;
    
    /**
     * Creates new form MainScreen
     * @param JFrameMainScreen
     * @param dataPanel
     * @param usuari
     * @param idUsuari
     */
    public SecondaryScreen(MainScreen JFrameMainScreen, int idUsuari) {
        initComponents();
//        this.usuari = usuari;
        this.idUsuari = idUsuari;
        this.JFrameMainScreen = JFrameMainScreen;
        setBounds(100, 120, 700, 650);
        tblAlojamientos.setModel(new AllotjamentTableModel((da.getAlojamientos(idUsuari))));  
        

//        this.dataPanel = dataPanel;
        
//        lstListaAlojamientos = new javax.swing.JList<>(); 
//        scrListaAlojamientos.setViewportView(lstListaAlojamientos);
        
//        lstListaAlojamientos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
//            @Override
//            public void valueChanged(ListSelectionEvent e) {
//                lstListaAlojamientosValueChanged(e);
//            }
//        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlojamientos = new javax.swing.JTable();
        btnShowInsertPanel = new javax.swing.JButton();

        setLayout(null);

        tblAlojamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAlojamientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlojamientosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlojamientos);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 446, 364);

        btnShowInsertPanel.setText("New...");
        btnShowInsertPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowInsertPanelActionPerformed(evt);
            }
        });
        add(btnShowInsertPanel);
        btnShowInsertPanel.setBounds(340, 420, 120, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowInsertPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowInsertPanelActionPerformed
        JFrameMainScreen.showInsertarAlojamiento();
    }//GEN-LAST:event_btnShowInsertPanelActionPerformed

    private void tblAlojamientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlojamientosMouseClicked
        AllotjamentTableModel atbm = (AllotjamentTableModel) tblAlojamientos.getModel();
        int selectedRowIndex = tblAlojamientos.getSelectedRow();
        //atbm.getValueAt(selectedRowIndex, 0);
        Alojamiento selectedAllotjament = atbm.getValueAtRow(selectedRowIndex);
        System.out.print("selected allotjament id: " + selectedAllotjament.getId());
        //System.out.print(((Main)this.getRootPane().getContentPane()));
//        ((Main)this.getRootPane().getContentPane()).showPnlDetallAllotjament(selectedAllotjament);
//        JFrameMainScreen.showPnlDetallAllotjament(selectedAllotjament);
        JFrameMainScreen.showDataPanel(selectedAllotjament);
    }//GEN-LAST:event_tblAlojamientosMouseClicked
    
//    public void setTitle(String title){
//        lblTitulo.setText(title + usuari);
//        lblTitulo.setFont(new Font("Segoe UI", Font.PLAIN, 24));
//    }

//    private void lstListaAlojamientosValueChanged(javax.swing.event.ListSelectionEvent evt) {                                                
//        //var alojamientos = da.getAlojamientos(usuari, idUsuari);
//        Alojamiento alojamientoSel = new Alojamiento();
//        JList lista = (JList) evt.getSource();
//        Object o = lista.getSelectedValue();
//        if (o.getClass().equals(Alojamiento.class))
//        {
//            alojamientoSel = (Alojamiento) o;
//        }
//        dataPanel.setName (alojamientoSel.getNom());
//    }                 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowInsertPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlojamientos;
    // End of variables declaration//GEN-END:variables
    private int idUsuari;
}