package spdvid.bkportal_di_dam;

import spdvid.bkportal_di_dam.dialogs.LoginDialog;
import spdvid.bkportal_di_dam.panels.SecondaryScreen;
import spdvid.bkportal_di_dam.panels.InsertarAlojamiento;
import spdvid.bkportal_di_dam.dto.Alojamiento;
import spdvid.bkportal_di_dam.dto.Usuari;
import spdvid.bkportal_di_dam.panels.DataPanel;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Fer
 */
public class MainScreen extends javax.swing.JFrame {

    private Usuari authenticatedUser = null;
    private SecondaryScreen homeScreen = null;
    private DataPanel dataPanel = null;
    private InsertarAlojamiento insertarAlojamiento = null;
   
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setBounds(400, 0, 700, 800);
        
        lblLink.setForeground(Color.BLUE.darker());
        lblLink.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        pnlMainScreen = new javax.swing.JPanel();
        lblLink = new javax.swing.JLabel();
        btnLoginDialog = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblLog = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_100x100.png"))); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(100, 0, 100, 100);

        pnlMainScreen.setLayout(null);
        getContentPane().add(pnlMainScreen);
        pnlMainScreen.setBounds(0, 120, 700, 650);

        lblLink.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLink.setText("Web de BK");
        lblLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLinkMouseClicked(evt);
            }
        });
        getContentPane().add(lblLink);
        lblLink.setBounds(310, 10, 130, 50);

        btnLoginDialog.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        btnLoginDialog.setText("Login");
        btnLoginDialog.setToolTipText("");
        btnLoginDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginDialogActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoginDialog);
        btnLoginDialog.setBounds(550, 10, 100, 40);

        btnLogout.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout);
        btnLogout.setBounds(550, 60, 100, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 110, 660, 40);
        getContentPane().add(lblLog);
        lblLog.setBounds(220, 60, 310, 20);

        lblBienvenida.setText("BIenvenido a la aplicación de viviendas de BK");
        lblBienvenida.setVisible(true);
        getContentPane().add(lblBienvenida);
        lblBienvenida.setBounds(190, 250, 310, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginDialogActionPerformed
        LoginDialog loginDialog = new LoginDialog(this, true);
        loginDialog.setVisible(true);
        if (authenticatedUser != null) {
            btnLoginDialog.setEnabled(false);
            btnLogout.setEnabled(true);
            lblLogo.setVisible(true);
            lblLog.setText("Bienvenido " + authenticatedUser.getNom());
            lblLog.setVisible(true);
            homeScreen = new SecondaryScreen(this, authenticatedUser.getId());
//            pnlMainScreen.removeAll();
            pnlMainScreen.add(homeScreen);
            pnlMainScreen.repaint();
        }
    }//GEN-LAST:event_btnLoginDialogActionPerformed

    private void lblLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLinkMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://paucasesnovescifp.cat/"));
        }catch (IOException | URISyntaxException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblLinkMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        authenticatedUser = null;
        btnLoginDialog.setEnabled(true);
        btnLogout.setEnabled(false);
        lblLog.setText("No hay un usuario activo");
//        lblLog.setVisible(false);
        pnlMainScreen.removeAll();
        pnlMainScreen.repaint();
    }//GEN-LAST:event_btnLogoutActionPerformed

    public MainScreen(JButton btnLoginDialog, JLabel lblLink, JLabel lblLogo, SecondaryScreen homeScreen, DataPanel dataPanel) throws HeadlessException {
        this.btnLoginDialog = btnLoginDialog;
        this.lblLink = lblLink;
        this.lblLogo = lblLogo;
        this.homeScreen = homeScreen;
        this.dataPanel = dataPanel;
    }

    public void bienvenidaUsuario(Usuari user){
        lblUsuario.setBounds(220,80,400,60);
        lblUsuario.setText("Bienvenido " + user.getNom() + ", esta es su zona personal");
        getContentPane().add(lblUsuario);
        lblUsuario.setVisible(true);
    }
    
    public void userLoggedIn(Usuari user) {
        authenticatedUser = user;
    }
   
    public void showListaAlojamientos(){
        pnlMainScreen.removeAll();
        pnlMainScreen.add(homeScreen);
        pnlMainScreen.repaint();
    }

    public void showDataPanel(Alojamiento alojamiento){
        dataPanel = new DataPanel(alojamiento, this);
        pnlMainScreen.removeAll();
        pnlMainScreen.add(dataPanel);
        pnlMainScreen.repaint();
    }    
    
    public void showInsertarAlojamiento() {
        pnlMainScreen.removeAll();
        insertarAlojamiento = new InsertarAlojamiento(this);
        pnlMainScreen.add(insertarAlojamiento);
        pnlMainScreen.repaint();
    }

    public Usuari getAuthenticatedUser() {
        return authenticatedUser;
    }
    
    public void reloadHomeScreen() {
        pnlMainScreen.removeAll();
        homeScreen = new SecondaryScreen(this, authenticatedUser.getId());
        pnlMainScreen.add(homeScreen);
        pnlMainScreen.repaint();
    }
    
    private void lstUsuarisValueChanged(javax.swing.event.ListSelectionEvent evt){
      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginDialog;
    private javax.swing.JButton btnLogout;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblLink;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlMainScreen;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel lblUsuario = new JLabel();
}